idf_component_register(
    SRCS
        "spiffs_utils.c"
        "app_main.c"
        "mqtt_client_handler.c"
        "wifi_provisioning.c"
        "dht11.c"
        "dht11_decode.c"
        "cert_manager.c"
        "time_sync.c"
    INCLUDE_DIRS
        "."
    PRIV_REQUIRES
        esp_driver_gpio
        esp_driver_rmt
        esp_event
        esp_netif
        lwip
        esp_rom
        esp_timer
        esp_wifi
        nvs_flash
        spiffs
)
